// <auto-generated />
namespace GymControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removechavedesnecessaria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removechavedesnecessaria));
        
        string IMigrationMetadata.Id
        {
            get { return "201803061045263_Remove chave desnecessaria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
