// <auto-generated />
namespace GymControl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Notnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notnull));
        
        string IMigrationMetadata.Id
        {
            get { return "201803231853208_Not null "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
